version: '3.8'

services:
  webcrawler:
    image: node:18-alpine # Usa uma imagem leve do Node.js versão 18
    container_name: webcrawler
    restart: unless-stopped
    ports:
      - "8001:8001" # Mapeia a porta do container para a máquina host
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Monta o diretório local no container
    environment:
      - ENV=dev
      - OPENAI_API_KEY=sk-proj-LMa2aJdKIHP6zQiqDLhMT3BlbkFJUZdswYvGhsDFK53UCnVE
      - PINECONE_API_KEY=pcsk_3BzD4N_UTQSiQHotzd8ygq2RdEzMZheV9VsniU8ydnz3T6f4qVM1C78pYkTBMcVgfqJffh
      - PINECONE_ENVIRONMENT=gcp-starter
      - PINECONE_INDEX=web-crawler
      - PORT=8001
      - URL=https://crawler.maquinadevendasdigital.com.br
    command: >
      sh -c "
      npm install &&
      npm start
      "
