version: '3.8'

services:
  webcrawler:
    image: node:18-alpine # Usa uma imagem leve do Node.js versão 18
    container_name: webcrawler
    restart: unless-stopped
    ports:
      - "8001:8001" # Mapeia a porta do container para a máquina host
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Monta o diretório local no container
    environment:
      - ENV=dev
      - OPENAI_API_KEY=
      - PINECONE_API_KEY=
      - PINECONE_ENVIRONMENT=gcp-starter
      - PINECONE_INDEX=web-crawler
      - PORT=8001
      - URL=https://crawler.xxxxxxxxxx.com.br
    command: >
      sh -c "
      if [ ! -f package.json ]; then
        echo 'package.json não encontrado. Criando um novo...';
        echo '{ \"scripts\": { \"start\": \"node index.js\" } }' > package.json; # Adiciona um script start básico
        npm install; # Instala as dependências do npm
      else
        echo 'package.json encontrado. Instalando dependências...';
        npm install; # Caso o package.json já exista, instala as dependências
      fi &&
      npm start;
      "
