ENV=dev
OPENAI_API_KEY=sk-proj-LMa2aJdKIHP6zQiqDLhMT3BlbkFJUZdswYvGhsDFK53UCnVE
PINECONE_API_KEY=pcsk_3BzD4N_UTQSiQHotzd8ygq2RdEzMZheV9VsniU8ydnz3T6f4qVM1C78pYkTBMcVgfqJffh
PINECONE_ENVIRONMENT=gcp-starter
PINECONE_INDEX=web-crawler
PORT=8001
URL=https://crawler.maquinadevendasdigital.com.br
